enum UserActionTypes {
    FETCH_USERS = 'USER-HOBBIES/USERS/FETCH_USERS',
    FETCH_USERS_SUCCESS = 'USER-HOBBIES/USERS/FETCH_USERS_SUCCESS',
    FETCH_USERS_ERROR = 'USER-HOBBIES/USERS/FETCH_USERS_ERROR',
    ADD_USER = 'USER-HOBBIES/USERS/ADD_USER',
    SELECT_USER = 'USER-HOBBIES/USERS/SELECT_USER',
    SELECT_USER_SUCCESS = 'USER-HOBBIES/USERS/SELECT_USER_SUCCESS',
    SELECT_USER_ERROR = 'USER-HOBBIES/USERS/SELECT_USER_ERROR',
    ADD_HOBBY ='USER-HOBBIES/USERS/ADD_HOBBY',
    REMOVE_HOBBY = 'USER-HOBBIES/USERS/REMOVE_HOBBY',
}

 export default UserActionTypes